# -*- coding: utf-8 -*-
"""Label Encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mo74oTvLgS-4YtInkqihD_rvoBUNqWCF

Label Encoding:
* converting the labels into numeric form
"""

# importing the dependencies
import pandas as pd
from sklearn.preprocessing import LabelEncoder

"""Label Encoding of Breast Cancer Dataset"""

# loading the data from csv file to dataframe
cancer_data = pd.read_csv('/content/data.csv')
cancer_data.head()

# finding the count of different labels
cancer_data['diagnosis'].value_counts()

# load the Label Encoder funtion
label_encode = LabelEncoder()
labels = label_encode.fit_transform(cancer_data.diagnosis)

# appending lables to the DataFrame
cancer_data['target'] = labels
cancer_data.head()

cancer_data['target'].value_counts()

"""Iris Data set for 3 Label"""

iris_data = pd.read_csv('/content/iris_data.csv')
iris_data.head()

iris_data['Species'].value_counts()

labels = label_encode.fit_transform(iris_data.Species)
iris_data['target'] = labels
iris_data.head()

iris_data['target'].value_counts()

