# -*- coding: utf-8 -*-
"""Seaborn Tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6GuBpyniUfcHMPWcb2kcT0ltanSXsuP

Seaborn:
  Data visualisation library

Importing library
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""Note: Seaborn has some built-in datasets"""

# total bill vs tip dataset
tips = sns.load_dataset('tips')

tips.head()

tips.size

# setting theme for plots
sns.set_theme()

# visualise the data
sns.relplot(data=tips, x = 'total_bill', y = 'tip', col = 'time', hue='smoker', style = 'smoker', size = 'size')

# load the iris dataset
iris = sns.load_dataset('iris')
iris.head()

"""Scatter Plot"""

sns.scatterplot(x = 'sepal_length', y = 'petal_length', hue = 'species', data = iris)

sns.scatterplot(x = 'sepal_length', y = 'petal_width', hue = 'species', data = iris)

# importing titanic dataset
titanic = sns.load_dataset('titanic')
titanic.head()

"""Count Plot"""

sns.countplot(x = 'class', data = titanic)

sns.countplot(x = 'survived', data = titanic)

"""Bar Chart"""

sns.barplot(x = 'sex', y = 'survived', hue = 'class', data = titanic)

# house price dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing_df = pd.DataFrame(housing.data, columns = housing.feature_names)
housing_df['Price'] =  housing.target
housing_df.head()

"""Distribution Plot"""

sns.distplot(housing_df['Price'])

"""Correlation:

  Positive Correlation
  
  Negative Correlation

Heat Map
"""

correlation = housing_df.corr()

# constructing Heap Map
plt.figure(figsize = (10, 10))
sns.heatmap(correlation, cbar = True, square = True, fmt = '.2f', annot = True, annot_kws = {'size' : 8}, cmap = 'Blues')

