# -*- coding: utf-8 -*-
"""Feature Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hEIHjEjUH7XO4ayPzvio3xIGdy-GkHGr

Mapping from textual data to reveal valued vectors is called feature extraction.

Bag Of Words (BOW) - List of unique words in the text corpus

Term Frequency - Inverse Document Frequency (TF - IDF) -> To count the number of times each word appears in a document

Term Frequency (TF) = Number of times term t appears in a document / Number of terms in the document

Inverse Document Frequency (IDF) = log(N / n), where N is the number of documents and n is number of documents a term t has appeared in
"""

